spring:  
  application:
    name: account-service
  cloud:
    consul:
      host: 192.168.64.5
      port: 8500
      # host: ${consule-host}
      # port: ${consule-port}
  output.ansi.enabled: ALWAYS