spring:  
  application:
    name: account-service
  cloud:
    consul:
      host: ${consule-host}
      port: ${consule-port}
      discovery:
        deregister: true
      # host: ${consule-host}
      # port: ${consule-port}
  output.ansi.enabled: ALWAYS